name: Mirror to Gitee

on:
  push:
    branches:
      - '*'   # 监听所有分支
  workflow_dispatch:

jobs:
  mirror:
    runs-on: ubuntu-latest
    steps:
      - name: Mirror to Gitee
        uses: Yikun/hub-mirror-action@v1.4
        with:
          src: lucky-cry/magisk-modules
          dst: lucky__cat/magisk-modules
          dst_token: ${{ secrets.GITEE_TOKEN }}
          force_update: true
          debug: true
          static_list: "magisk-modules"
          account_type: user 